services:
  - type: web
    name: personalized-news-aggregator
    env: python
    root: personalized_news_aggregator
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
